[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "shelf"
version = "1.0.0"
description = "An app for book lovers."
readme = "README.md"
requires-python = ">=3.10"
authors = [
    { name = "Ángel" } 
]
license = { text = "MIT" } 

dependencies = [
    "nicegui",
    "sqlalchemy",
    "psycopg2-binary",
    "werkzeug",
    "python-dotenv",
    "requests"
]

[project.optional-dependencies]
dev = [
    "pytest",
]

[tool.setuptools.packages.find]
where = ["."]