[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "shelf"
version = "1.2.0"
description = "An app for book lovers."
readme = "README.md"
requires-python = ">=3.10,<4.0"
authors = [
    { name = "Ángel" } 
]
license = { text = "MIT" } 

dependencies = [
    "nicegui",
    "sqlalchemy",
    "werkzeug",
    "python-dotenv",
    "requests",
    "psycopg[binary] (>=3.3.6,<4.0.0)"
]

[project.optional-dependencies]
dev = [
    "pytest",
]

[tool.setuptools.packages.find]
where = ["."]

[tool.poetry]
package-mode = false